spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(rm9ONo55pV9b3a0lwpAbZm3abaYR9+LJPpJ/tx+B//lopeaL/hOp4bZG9f1rHeaE727yKzV62C4xDn1tkE862s59BvKuZWG+LLDnY/TFt8nlmvpsppPVSw==)
    username: ENC(R5wYtFLPzE8j1dYaLN8JHw==)
    password: ENC(2VRZJBlof9rNUyol/Olzw9LAaWzcDfRC)
  data:
    redis:
      host: ENC(ItcOHb8ScqGMgddHtdmOvWENNiyPIm+U)
      port: ENC(wGSwwvSRNC7IppcI+oLeKA==)
mybatis:
  type-aliases-package: com.flab.idolu.domain.*.entity, com.flab.idolu.domain.*.dto.response
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: mybatis/mapper/**/*.xml
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(FiwzInS7wI6suzDGxytHgTFcFsLZbwoo)
    username: ENC(NrsbtZBR03MLlkYUY8dkhN0OVbV8CDEc)
    password: ENC(q9OlsY6oZ49E13S0FkkItrCRpzIThVwK)
  data:
    redis:
      host: ENC(UhS802zm/QSPP5lnV0jTb1jVJWx6xA3L)
      port: ENC(Hs+PeNOpl44nxiRMt5nz9NmBSU7lOPv1)
      password: ENC(redispassword)

server:
  port: 8080
