spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(qWDwD8bHKhIrpQH3bQztE1PKAr4Ci9oAWu42essW/99Sstla3WW0NQ96J1BDyvnk9QWRVVKL8zLmbrDgTNv1a6yEKXvNXfHx)
    username: ENC(R5wYtFLPzE8j1dYaLN8JHw==)
    password: ENC(2VRZJBlof9rNUyol/Olzw9LAaWzcDfRC)
  data:
    redis:
      host: ENC(ItcOHb8ScqGMgddHtdmOvWENNiyPIm+U)
      port: ENC(wGSwwvSRNC7IppcI+oLeKA==)
      password: ENC(CfXONUwAUri6U2vKhaaFE5Hvcqm/ArWF)
mybatis:
  type-aliases-package: com.flab.idolu.domain.*.entity, com.flab.idolu.domain.*.dto.response
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: mybatis/mapper/**/*.xml
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: health
---

spring:
  config:
    activate:
      on-profile: prod1
  datasource:
    source:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(bYq1JS4dQAYXjHmn1mDlSPFuiH6jgcX6G7bTFiNTttfKZmfdx+Wz7CtWhZSvkA+7zzN/cWLJxb+VNJLBHYvNLr2Tgc2f5lF5)
      username: ENC(v1Qf/pZcdMx6bZ2sth8h2A==)
      password: ENC(YEslivkCss7owXDEzcufYjDhOpGmh12f)
    replica:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(V/2TFZGXJHrabvQo+mIp9LrP3dGMzdCSuaf9LsJVt0yOzvIyC+ndsMBt2AvvhaCF)
      username: ENC(nMwtinItmDzyc00a3SmltA==)
      password: ENC(zo1PkiP39isPi0iRmU5hgkdjpsgmxSYY)
  data:
    redis:
      host: ENC(X5l3B3IOUY0jRMkCuayh2gqCPCD6mIf9)
      port: ENC(HdD4vqgrg4X5YTE26mKNkw==)
      password: ENC(1KIy5fYk1jIpW44zkkL8qs7uI5motiCK)

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: prod2
  datasource:
    source:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(bYq1JS4dQAYXjHmn1mDlSPFuiH6jgcX6G7bTFiNTttfKZmfdx+Wz7CtWhZSvkA+7zzN/cWLJxb+VNJLBHYvNLr2Tgc2f5lF5)
      username: ENC(v1Qf/pZcdMx6bZ2sth8h2A==)
      password: ENC(YEslivkCss7owXDEzcufYjDhOpGmh12f)
    replica:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(V/2TFZGXJHrabvQo+mIp9LrP3dGMzdCSuaf9LsJVt0yOzvIyC+ndsMBt2AvvhaCF)
      username: ENC(nMwtinItmDzyc00a3SmltA==)
      password: ENC(zo1PkiP39isPi0iRmU5hgkdjpsgmxSYY)
  data:
    redis:
      host: ENC(X5l3B3IOUY0jRMkCuayh2gqCPCD6mIf9)
      port: ENC(HdD4vqgrg4X5YTE26mKNkw==)
      password: ENC(1KIy5fYk1jIpW44zkkL8qs7uI5motiCK)

server:
  port: 8081